name: python_project_template
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - expat=2.7.1
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openssl=3.0.16
  - pandas=2.2.3
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2024.1
  - pyyaml=6.0.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - jsonargparse==4.40.0
prefix: /home/schelian/anaconda3/envs/python_project_template
